# Generated by Django 4.1 on 2024-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog-slug', unique=True),
            preserve_default=False,
        ),
    ]
