# Generated by Django 4.1 on 2024-07-12 03:34

"""from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_slug'),
    ]

    operations = [
    ]"""
from django.db import migrations
from django.utils.text import slugify

def generate_unique_slug(Post, title, original_slug):
    slug = original_slug
    counter = 1
    while Post.objects.filter(slug=slug).exists():
        slug = f"{original_slug}-{counter}"
        counter += 1
    return slug

def populate_unique_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        if not post.slug:
            original_slug = slugify(post.title)
            post.slug = generate_unique_slug(Post, post.title, original_slug)
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_slug'),  # Adjust this based on your latest migration
    ]

    operations = [
        migrations.RunPython(populate_unique_slugs),
    ]
