# Generated by Django 4.1 on 2024-07-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_populate_unique_slugs'),
    ]

    operations = [
    ]
